var constants = {
    SEARCH_BOOK:'SEARCH_BOOK',
    SEARCH_BOOK_ERROR:'SEARCH_BOOK_ERROR',
    SEARCH_BOOK_RESPONSE_RECEIVED:'SEARCH_BOOK_RESPONSE_RECEIVED',
    REMOVE_SEARCH_RESULT:'REMOVE_SEARCH_RESULT',
    START_AUTHENTICATING:'START_AUTHENTICATING',
    AUTHENTICATION_SUCCESSFUL:'AUTHENTICATION_SUCCESSFUL',
    AUTHENTICATION_FAILED:'AUTHENTICATION_FAILED',
    ALREADY_LOGIN:'ALREADY_LOGIN',
    LOGOUT:'LOGOUT',
    LOGOUT_SUCCESSFUL:'LOGOUT_SUCCESSFUL',
    LOGOUT_ERROR:'LOGOUT_ERROR'
}

export default constants;