var constants = {
    SEARCH_BOOK:'SEARCH_BOOK',
    SEARCH_BOOK_ERROR:'SEARCH_BOOK_ERROR',
    SEARCH_BOOK_RESPONSE_RECEIVED:'SEARCH_BOOK_RESPONSE_RECEIVED',
    REMOVE_SEARCH_RESULT:'REMOVE_SEARCH_RESULT'

}

export default constants;